# Sample Slurm configuraton file (slurm.conf)

# Control Machine
ControlMachine=controller
ClusterName=clustername

# Communication settings
AuthType=auth/munge
CryptoType=crypto/munge
SlurmdPort=6818
SlurmctldPort=6817
SlurmUser=64030

# Job scheduling
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core

# Elastic Computing
ElasticComputing=yes         # Enable Elastic Computing
SuspendExcuse=NodeIdle       # Suspend nodes when idle
SuspendProgram=/etc/slurm/manage_lxd.sh stop
ResumeProgram= /etc/slurm/manage_lxd.sh start
SuspendTimeout=80          # Time before suspending idle nodes (80 seconds)
ResumeTimeout=60            # Time to wait for node to come up (60 seconds)
SuspendRate=1               # Number of nodes suspended simultaneously
ResumeRate=1                # Number of nodes resumed simultaneously

# Logging
SlurmdLogFile=/var/log/slurm/slurmd.log
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdPidFile=/var/run/slurmd.pid
SlurmctldPidFile=/var/run/slurmctld.pid
#StateSaveLocation=/var/spool/slurmctld
SlurmctldTimeout=300
SlurmdTimeout=300
MessageTimeout=60

# Node and partition definitions
NodeName=node[1-100].c1xacc355.com CPUs=4  RealMemory=8192 
PartitionName=debug Nodes=node[1-100].c1xacc355.com Default=YES MaxTime=INFINITE State=UP

# Other settings
ProctrackType=proctrack/pgid
TaskPlugin=task/affinity
JobAcctGatherType=jobacct_gather/none
